// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: notification.sql

package database

import (
	"context"
)

const sendNotification = `-- name: SendNotification :exec
SELECT id, sent_at, sender_id, receiver_id, content FROM messages
`

func (q *Queries) SendNotification(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, sendNotification)
	return err
}
